[tcmalloc] move internal tools to separate build module
В [upstream](https://github.com/google/tcmalloc/blob/f69ca17d4c3b9024544039f61fe7af9060d5b531/tcmalloc/internal/BUILD#L457-L475) разбиение сделано умом, но смысла в этом не много - поэтому все слито в один util-модуль.

---

Пришлось прописать `IF (OS_LINUX)` в ya.make'и модулей, потому что без этого сборка новых модулей падала

```
/home/ilikepugs/arc3/arcadia/contrib/libs/tcmalloc/tcmalloc/internal/config.h:105:2: error:
"TCMalloc is only supported on Linux."105 | #error "TCMalloc is only supported on Linux."|
```

Разобраться, почему сборка условного `malloc_extension/`  и прочих старых модулей под `darwin` не падала я не осилил.
commit_hash:1d07360eba1ef59a6d6013da1c82ea5f57bb58f6

(cherry picked from commit 672cee2005cf67f550ec4d92b6585053278858a4)