merge to stable-22-2
[loadtest] NBS-3062: custom core pattern
REVIEW: 2367932

[yatest] NBS-3062: write backtrace to html with text mode
Если бинарь собирается под python3, то при попытке сдампить корку в html-файл, получаем ошибку:
```
Traceback (most recent call last):
 File "library/python/testing/yatest_common/yatest/common/process.py", line 395, in verify_no_coredumps
 self._recover_core()
 File "library/python/testing/yatest_common/yatest/common/process.py", line 292, in _recover_core
 backtrace_to_html(bt_filename, pbt_filename)
 File "library/python/testing/yatest_common/yatest/common/process.py", line 737, in backtrace_to_html
 coredump_filter.filter_stackdump(bt_filename, stream=afile)
 File "sandbox/sdk2/helpers/coredump_filter/__init__.py", line 1294, in filter_stackdump
 return dumper.dump()
 File "sandbox/sdk2/helpers/coredump_filter/__init__.py", line 1130, in dump
 html_prolog(self.stream, self.timestamp)
 File "sandbox/sdk2/helpers/coredump_filter/__init__.py", line 927, in html_prolog
 stream.write(prolog.format(
TypeError: a bytes-like object is required, not 'str'
```
REVIEW: 2370907

[harness] NBS-3062: forward custom core pattern to yatest.process
REVIEW: 2367454

DEVTOOLSSUPPORT-15739, NBS-3062: custom core pattern
REVIEW: 2367120

REVIEW: 2396836
x-ydb-stable-ref: c381d0acc3d8c7a34a2f1f7a34e7f7b1b177c047